apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-json
  template:
    metadata:
      labels:
        app: echo-json
    spec:
      containers:
      - name: echo-json
        image: rossmcd/echo-json:latest
        ports:
        - containerPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  name: echo-json
  labels:
    app: echo-json
spec:
  type: LoadBalancer
  ports:
  - port: 8889
    targetPort: 8889
    protocol: TCP
    name: http
  selector:
    app: echo-json
